POST https://localhost:8081/api/airports
Content-Type: application/json

{
  "uuid": "{{$random.uuid}}",
  "desc": "{{$random.alphabetic(10)}}",
  "desc1": "{{$random.alphanumeric(10)}}",
  "desc2": "{{$random.numeric(10)}}",
  "base64": "{{$imageToBase64(E:\\image\\test.jpg)}}",
  "value": "content",
  "ts": "{{$timestamp}}",
  "price2": {{$randomInt}}
}